---
language: general
dependency:
  name: galaxy
driver:
   name: docker
lint:
  name: yamllint
platforms:
  - name: cent7instance
    image: centos:7
  - name: cent6instance
    image: centos:6
  - name: ubuinstance
    image: ubuntu:14.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
