---

#5.1.1 Ensure cron daemon is enabled (Scored)

- name: Ensure crond is  installed on CentOS distros
  yum:
    name: cronie
    state: present

- name : Ensure Cron daemon is enabled on CentOS Distros
  service:
    name: crond
    state: started
    enabled: yes

# 5.1.2 Ensure permissions on /etc/crontab are configured 



- name: Ensure permissions on /etc/crontab are configured in CentOS Distros
  ansible.builtin.file:
    path: /etc/crontab
    owner: root
    group: root
    mode: '0600'   

# 5.2 SSH Server Configuration


- name : Ensure Cron daemon is enabled on ubuntu Distros
  service:
    name: sshd
    state: started
    enabled: yes

- name: Ensure permissions on /etc/ssh/sshd_config are configured in CentOS Distros  
  ansible.builtin.file:
    path: /etc/ssh/sshd_config
    owner: root
    group: root 
    mode: '0600' 

- name: Ensure SSH loglevel is set to info 
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: '#(LogLevel INFO)'
    line: '\1'
    backrefs: yes

- name:  Ensure SSH X11 forwarding is disabled in CentOS Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: 'X11Forwarding\ yes'
    line: 'X11Forwarding no'

- name: Ensure SSH MaxAuthTries is set to 4 or less in CentOS Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    line: 'MaxAuthTries 4'

- name: Ensure SSH IgnoreRhosts is enabled in CentOS Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: '#(IgnoreRhosts yes)'
    line: '\1'
    backrefs: yes

- name: Ensure SSH HostbasedAuthentication is disabled in CentOS Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: 'HostbasedAuthentication"'
    line: 'HostbasedAuthentication no'

- name:  Ensure SSH root login is disabled in CentOS Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: 'PermitRootLogin"'
    line: 'PermitRootLogin no'

- name:  PermitEmptyPasswords no
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: 'PermitEmptyPasswords no"'
    line: 'PermitEmptyPasswords no'

- name:  Ensure SSH PermitUserEnvironment is disabled in CentOS Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: 'PermitUserEnvironment no"'
    line: 'PermitUserEnvironment no'

- name: Ensure only approved ciphers are used in CentOS Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: 'Ciphers'
    line: 'Ciphers aes256-ctr,aes192-ctr,aes128-ctr'


- name: Ensure only approved MAC algorithms are used in CentOS Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: 'MACs'
    line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'

  
- name: Ensure SSH Idle Timeout Interval is configured in CentOS Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: 'ClientAliveInterval'
    line: 'ClientAliveInterval 300'
  tags:
    ssh-hard
