---

- name: Ensure EPEL is enabled on RedHat distros
  yum:
    name: epel-release
    state: present

- name: Ensure basic packages are installed on RedHat distros
  yum:
    name: "{{list_of_packages}}"
    state: present

- name: Copying MOTD file on CentOS distros
  template: src=motd.j2 dest="/etc/motd"
  tags:
    motd

- name: starting firewalld services in CentOS distros
  service:
    name=firewalld state=stopped enabled=false
