
---

- name: Install cron in Ubuntu Distros 
  apt:
    name: cron
    state: present

- name : Ensure Cron daemon is enabled on ubuntu Distros
  service:
    name: cron
    state: started
    enabled: yes


- name : Ensure SSH  daemon is enabled on ubuntu Distros
  service:
    name: ssh
    state: started
    enabled: yes


- name: Ensure permissions on /etc/crontab are configured in Ubuntu Distros
  ansible.builtin.file:
    path: /etc/crontab
    owner: root
    group: root
    mode: '0600'    

# 5.2 SSH Server Configuration hardening

- name: Ensure permissions on /etc/ssh/sshd_config are configured in Ubuntu Distros
  ansible.builtin.file:
    path: /etc/ssh/sshd_config
    owner: root
    group: root 
    mode: '0600'

- name: Ensure SSH loglevel is set to info in Ubuntu Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: '^Protocol 2'
    line: 'Protocol 2'

- name:  Ensure SSH X11 forwarding is disabled in Ubuntu Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: 'X11Forwarding\ yes'
    line: 'X11Forwarding no'

- name: Ensure SSH MaxAuthTries is set to 4 or less in Ubuntu Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    line: 'MaxAuthTries 4'

- name: Ensure SSH IgnoreRhosts is enabled in Ubuntu Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: '#(IgnoreRhosts yes)'
    line: '\1'
    backrefs: yes

- name: Ensure SSH HostbasedAuthentication is disabled in Ubuntu Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: 'HostbasedAuthentication"'
    line: 'HostbasedAuthentication no'

- name:  Ensure SSH root login is disabled in Ubuntu Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: 'PermitRootLogin"'
    line: 'PermitRootLogin no'

- name:  Ensure SSH PermitEmptyPasswords no in Ubuntu Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: 'PermitEmptyPasswords no"'
    line: 'PermitEmptyPasswords no'


- name:  Ensure SSH PermitUserEnvironment is disabled in Ubuntu Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: 'Ciphers'
    line: 'Ciphers aes256-ctr,aes192-ctr,aes128-ctr'

- name: Ensure only approved MAC algorithms are used in Ubuntu Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: 'MACs'
    line: 'MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com'

- name: Ensure SSH Idle Timeout Interval is configured in Ubuntu Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: 'ClientAliveInterval'
    line: 'ClientAliveInterval 300'

- name: Ensure SSH Idle Timeout Interval is configured in Ubuntu Distros
  lineinfile:
    dest: '/etc/ssh/sshd_config'
    regexp: 'ClientAliveCountMax'
    line: 'ClientAliveCountMax 0'
  tags:
    ssh-hard-ubu